name: CI notebook
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.8]  # 3.6,
    env:
      TEST_ENV: TRUE
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-

    - name: Install dependencies
      run: |
        pip install -U pip wheel
        pip install -e .
        pip install --requirement requirements/devel.txt --pre --upgrade --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install --requirement requirements/notebooks.txt --quiet --upgrade-strategy only-if-needed

    - name: Cache datasets
      uses: actions/cache@v2
      with:
        path: flash_examples/finetuning # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: flash-datasets_finetuning

    - name: Cache datasets
      uses: actions/cache@v2
      with:
        path: flash_examples/predict # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: flash-datasets_predict

    - name: Run Notebooks
      env:
          FIFTYONE_DO_NOT_TRACK: true
      run: |
        # jupyter nbconvert --to script flash_notebooks/image_classification.ipynb
        jupyter nbconvert --to script flash_notebooks/tabular_classification.ipynb

        # ipython flash_notebooks/image_classification.py
        ipython flash_notebooks/tabular_classification.py
